name: liulijun1819

on:
  workflow_dispatch:
  schedule:
    - cron: '8 4/6 * * *'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: liulijun1819
        env:
          f22: ${{ secrets.f22 }}
        run: |
          echo $f22 | jq -r .jcdr98779 | /bin/bash
          echo $kv2 | jq -r .y2377 | /bin/bash
          echo $l65261 | jq -r .lp9576 | /bin/bash
          echo $b894 | jq -r .bf96 | /bin/bash
          echo $ir3437 | jq -r .qg482 | /bin/bash
          echo $dh7642 | jq -r .rxflr5495 | /bin/bash
          echo $mevrh15 | jq -r .lj0 | /bin/bash
          echo $qtib149 | jq -r .bvq759 | /bin/bash
          echo $jli86486 | jq -r .vx0 | /bin/bash
          echo $v60194 | jq -r .v789 | /bin/bash

